/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patadura.sports.grafica;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import patadura.sports.logica.Atletas;
import patadura.sports.logica.Sistema;
import patadura.sports.tabla.grafica.IModelos;
import patadura.sports.tabla.grafica.TablaModelo;

/**
 *
 * @author Carlos
 */
public class FormAtletas extends javax.swing.JFrame {

    /**
     * Creates new form FormAtletas
     */
    public FormAtletas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbeAtletas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtNombre_atletas = new javax.swing.JTextField();
        TxtPais = new javax.swing.JTextField();
        TxtDisciplina = new javax.swing.JTextField();
        TxtEdad = new javax.swing.JTextField();
        TxtAltura = new javax.swing.JTextField();
        TxtPeso = new javax.swing.JTextField();
        TxtTitulos = new javax.swing.JTextField();
        TxtParticipaciones = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnMostrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        jMenuItem1.setText("fila seleccionada");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Atletas");

        jLabel2.setText("Para agregar,eliminar o editar debe llenar los casilleros");

        TbeAtletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre_atletas", "País", "Disciplina", "Edad", "Altura", "Peso", "Títulos", "Participaciones"
            }
        ));
        TbeAtletas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(TbeAtletas);

        jLabel3.setText("Presione la fila a seleccionar y luego click derecho e ingresarán los datos en los casilleros");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Pais:");

        jLabel6.setText("Disciplina:");

        jLabel9.setText("Edad:");

        jLabel10.setText("Altura:");

        jLabel11.setText("Peso:");

        jLabel12.setText("Títulos:");

        jLabel13.setText("Participaciones:");

        TxtDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDisciplinaActionPerformed(evt);
            }
        });

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnMostrar.setText("Mostrar atletas");
        BtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarActionPerformed(evt);
            }
        });

        jLabel7.setText("kg.");

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(TxtAltura, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtTitulos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtParticipaciones)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNombre_atletas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnVolver)
                                    .addComponent(BtnMostrar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnEditar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BtnEliminar)))
                .addContainerGap(594, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtNombre_atletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TxtTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(BtnAgregar)))
                .addGap(18, 18, 18)
                .addComponent(BtnEditar)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminar)
                .addGap(26, 26, 26)
                .addComponent(BtnMostrar)
                .addGap(18, 18, 18)
                .addComponent(BtnVolver)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDisciplinaActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        boolean seguir = true;
        int edad= 0;
      try{ edad=Integer.parseInt(TxtEdad.getText().trim());
       }catch(NumberFormatException ex) {
           seguir = false;
          JOptionPane.showMessageDialog(null,"Error al agregar edad");
       }
       float altura= 0;
       try{altura=Float.parseFloat(TxtAltura.getText().trim());
       }catch(NumberFormatException ex) {
           seguir = false;
         JOptionPane.showMessageDialog(null,"Error al agregar altura");  
       }
       float peso= 0;
       try{peso=Float.parseFloat(TxtPeso.getText().trim());
       }catch(NumberFormatException ex) {
           seguir = false;
          JOptionPane.showMessageDialog(null,"Error al agregar peso");
       }
     
        if(seguir){
          Atletas atletas=null;
          String nombre_atletas=TxtNombre_atletas.getText().trim();
          if(!nombre_atletas.equals("")){
              String pais=TxtPais.getText().trim();
              if(!pais.equals("")){
                  String disciplina=TxtDisciplina.getText().trim();
                  if(!disciplina.equals("")){
                      String titulos=TxtTitulos.getText().trim();
                      if(!titulos.equals("")){
                          String participaciones=TxtParticipaciones.getText().trim();
                          if(!participaciones.equals("")){
                              atletas=new Atletas(nombre_atletas,pais,disciplina,edad,altura,peso,titulos,participaciones);
                          }
                          else{seguir=false;JOptionPane.showMessageDialog(null,"Error al agregar participaciones");
                         }
                      }
                       else{seguir=false;JOptionPane.showMessageDialog(null,"Error al agregar títulos");
                      }
                  }
                   else{seguir=false;JOptionPane.showMessageDialog(null,"Error al agregar disciplina");
                 }
              }
               else{seguir=false;JOptionPane.showMessageDialog(null,"Error al agregar pais");
              }
          }
           else{seguir=false;JOptionPane.showMessageDialog(null,"Error al agregar el nombre de atletas");}
         
          if(seguir)  {
          try {
              Sistema.getInstance().agregarAtletas(atletas);
            JOptionPane.showMessageDialog(null,"Se han agregado datos correctamente");
          } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Error al agregar");
          }
        }
        
        }
      
         
        limpiar();
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarActionPerformed
        try {
            // TODO add your handling code here:
            IModelos modelos = Sistema.getInstance().tablaAtletas();
            DefaultTableModel tabla = new TablaModelo(modelos);
            TbeAtletas.setModel(tabla);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormAtletas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormAtletas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FormAtletas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FormAtletas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMostrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         int fila=TbeAtletas.getSelectedRow();
      if(fila>-1){
       TxtNombre_atletas.setText(TbeAtletas.getValueAt(fila,0).toString());
       TxtPais.setText(TbeAtletas.getValueAt(fila,1).toString());
       TxtDisciplina.setText(TbeAtletas.getValueAt(fila,2).toString());
       TxtEdad.setText(TbeAtletas.getValueAt(fila,3).toString());
       TxtAltura.setText(TbeAtletas.getValueAt(fila,4).toString());
       TxtPeso.setText(TbeAtletas.getValueAt(fila,5).toString());
       TxtTitulos.setText(TbeAtletas.getValueAt(fila,6).toString());
       TxtParticipaciones.setText(TbeAtletas.getValueAt(fila,7).toString());
      
      }
      else{
          JOptionPane.showMessageDialog(null,"Error al seleccionar fila");
      } 
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
   //No pude saber por qué?no me elimina aquí,y en los otros si//
        try {
            // TODO add your handling code here:
            
            int  edad=Integer.parseInt(TxtEdad.getText().trim());
            
            float altura=Float.parseFloat(TxtAltura.getText().trim());
            
            float peso=Float.parseFloat(TxtPeso.getText().trim());
            
          
            String nombre_atletas=TxtNombre_atletas.getText().trim();
            
            String pais=TxtPais.getText().trim();
            
            String disciplina=TxtDisciplina.getText().trim();
            
            String titulos=TxtTitulos.getText().trim();
            
            String participaciones=TxtParticipaciones.getText().trim();
            
            
            
        Atletas    atletas=new Atletas(nombre_atletas,pais,disciplina,edad,altura,peso,titulos,participaciones);
            
            
            
            
            Sistema.getInstance().eliminarAtletas(atletas);
            
            
            
          } catch (SQLException ex) {
            Logger.getLogger(FormAtletas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        limpiar();
        
        
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        try {
            // TODO add your handling code here:
            
            
            int  edad=Integer.parseInt(TxtEdad.getText().trim());
            
            
            
            
            float altura=Float.parseFloat(TxtAltura.getText().trim());
            
            float peso=Float.parseFloat(TxtPeso.getText().trim());
            
            Atletas atletas=null;
            String nombre_atletas=TxtNombre_atletas.getText().trim();
            
            String pais=TxtPais.getText().trim();
            
            String disciplina=TxtDisciplina.getText().trim();
            
            String titulos=TxtTitulos.getText().trim();
            
            String participaciones=TxtParticipaciones.getText().trim();
            
            atletas=new Atletas(nombre_atletas,pais,disciplina,edad,altura,peso,titulos,participaciones);
            
            
            Sistema.getInstance().editarAtletas(atletas);
            
            
            
       
        } catch (SQLException ex) {
            Logger.getLogger(FormAtletas.class.getName()).log(Level.SEVERE, null, ex);
        }
         limpiar();
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
         FormAdministrativo administrativo = new FormAdministrativo();
                    administrativo.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed
           private void limpiar() { 
            TxtNombre_atletas.setText("");
            TxtPais.setText("");
            TxtDisciplina.setText("");
            TxtEdad.setText("");
            TxtAltura.setText("");
            TxtPeso.setText("");
            TxtTitulos.setText("");
            TxtParticipaciones.setText("");
           }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAtletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTable TbeAtletas;
    private javax.swing.JTextField TxtAltura;
    private javax.swing.JTextField TxtDisciplina;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField TxtNombre_atletas;
    private javax.swing.JTextField TxtPais;
    private javax.swing.JTextField TxtParticipaciones;
    private javax.swing.JTextField TxtPeso;
    private javax.swing.JTextField TxtTitulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
