/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patadura.sports.grafica;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import patadura.sports.logica.Paises;
import patadura.sports.logica.Sistema;
import patadura.sports.tabla.grafica.IModelos;
import patadura.sports.tabla.grafica.TablaModelo;

/**
 *
 * @author Carlos
 */
public class FormPaises extends javax.swing.JFrame {

    /**
     * Creates new form FormPaises
     */
    public FormPaises() throws ClassNotFoundException, SQLException, InstantiationException {
        try {
            initComponents();
            IModelos modelos = Sistema.getInstance().tablaPaises();
            DefaultTableModel tabla = new TablaModelo(modelos);
            TbePaises.setModel(tabla);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtPoblacion = new javax.swing.JTextField();
        TxtContinente = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbePaises = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnMostrar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();

        jMenuItem1.setText("Fila seleccionada");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Países");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Población:");

        jLabel4.setText("Continente:");

        TxtPoblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPoblacionActionPerformed(evt);
            }
        });

        TxtContinente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContinenteActionPerformed(evt);
            }
        });

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        TbePaises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre ", "Población", "Continente "
            }
        ));
        TbePaises.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(TbePaises);

        jLabel5.setText("Para agregar,editar o eliminar debe llenar los casilleros");

        jLabel6.setText("Presione la fila a seleccionar y luego click derecho e ingresarán los datos en los casilleros");

        BtnMostrar.setText("Mostrar países");
        BtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarActionPerformed(evt);
            }
        });

        BtnVolver.setText("Volver al menú");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEliminar)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(BtnVolver))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtNombre))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(TxtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtContinente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(BtnEditar))
                                    .addComponent(BtnMostrar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BtnAgregar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(BtnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEditar)
                        .addGap(13, 13, 13)
                        .addComponent(BtnEliminar)
                        .addGap(39, 39, 39)
                        .addComponent(BtnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtContinenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContinenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContinenteActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        boolean seguir=true;
        int poblacion=0;
      try  { poblacion =Integer.parseInt(TxtPoblacion.getText().trim());
        }catch (NumberFormatException ex) {
            seguir=false;
        JOptionPane.showMessageDialog(null,"Error al agregar");
        }
      if(seguir){
          Paises paises=null;
      
        String nombre = TxtNombre.getText().trim();
      if(!nombre.equals("")) {
            String continente = TxtContinente.getText().trim();
            if(!continente.equals("")){
                paises = new Paises(nombre,poblacion,continente);  
            }
            else{seguir=false;
            JOptionPane.showMessageDialog(null,"Error al agregar");
            }
            }
      else{seguir=false;
      JOptionPane.showMessageDialog(null,"Error al agregar");}
      
            
             if(seguir)  {
          try {
              Sistema.getInstance().agregarPaises(paises);
            JOptionPane.showMessageDialog(null,"Se han agregado datos correctamente");
          } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Error al agregar");
          }
        }
        
        }
      limpiar();
      
        
       
        
        
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
         
       
            // TODO add your handling code here:
             boolean seguir=true;
        int poblacion=0;
      try  { poblacion =Integer.parseInt(TxtPoblacion.getText().trim());
        }catch (NumberFormatException ex) {
            seguir=false;
        JOptionPane.showMessageDialog(null,"Error al editar");
        }
      if(seguir){
          Paises paises=null;
      
        String nombre = TxtNombre.getText().trim();
      if(!nombre.equals("")) {
            String continente = TxtContinente.getText().trim();
            if(!continente.equals("")){
                paises = new Paises(nombre,poblacion,continente);  
            }
            else{seguir=false;
            JOptionPane.showMessageDialog(null,"Error al editar");
            }
            }
      else{seguir=false;
      JOptionPane.showMessageDialog(null,"Error al editar");}
      
            
        if(seguir)  {
          try {
              Sistema.getInstance().editarPaises(paises);
            JOptionPane.showMessageDialog(null,"Se han editado datos correctamente");
          } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Error al editar");
          }
        }
        
        }
      limpiar();
      

  
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        
       
            // TODO add your handling code here:
        boolean seguir=true;
        int poblacion=0;
      try  { poblacion =Integer.parseInt(TxtPoblacion.getText().trim());
        }catch (NumberFormatException ex) {
            seguir=false;
        JOptionPane.showMessageDialog(null,"Error al eliminar");
        }
      if(seguir){
          Paises paises=null;
      
        String nombre = TxtNombre.getText().trim();
      if(!nombre.equals("")) {
            String continente = TxtContinente.getText().trim();
            if(!continente.equals("")){
                paises = new Paises(nombre,poblacion,continente);  
            }
            else{seguir=false;
            JOptionPane.showMessageDialog(null,"Error al eliminar");
            }
            }
      else{seguir=false;
      JOptionPane.showMessageDialog(null,"Error al eliminar");}
      
            
            
        if(seguir)  {
          try {
              Sistema.getInstance().eliminarPaises(paises);
            JOptionPane.showMessageDialog(null,"Se han eliminado datos correctamente");
          } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Error al eliminar");
          }
        }
        
        }
      limpiar();
      
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void TxtPoblacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPoblacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPoblacionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here
      int fila=TbePaises.getSelectedRow();
      if(fila>-1){
       TxtNombre.setText(TbePaises.getValueAt(fila,0).toString());
       TxtPoblacion.setText(TbePaises.getValueAt(fila,1).toString());
       TxtContinente.setText(TbePaises.getValueAt(fila,2).toString());
      }
      else{
          JOptionPane.showMessageDialog(null,"Error al seleccionar fila");
      } 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarActionPerformed
        try {
            // TODO add your handling code here:
            IModelos modelos = Sistema.getInstance().tablaPaises();
            DefaultTableModel tabla = new TablaModelo(modelos);
            TbePaises.setModel(tabla);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_BtnMostrarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        FormAdministrativo administrativo = new FormAdministrativo();
                    administrativo.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed
        private void limpiar() {
        TxtNombre.setText("");
        TxtPoblacion.setText("");
         TxtContinente.setText("");
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormPaises().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(FormPaises.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTable TbePaises;
    private javax.swing.JTextField TxtContinente;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPoblacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
